version: 2
jobs:
  zip:
    machine: true
    steps:
      - checkout
      - run:
          name: Create & Place a ZIP into bin
          command: |
            if [[ $(git log -1 --pretty=%B) != *"Zipped"* ]]; then
              zip bin/lambda.zip logdna_cloudwatch.py
              git config --global user.email "samir.musali@logdna.com"
              git config --global user.name "Samir Musali"
              git add .
              git commit -m 'Zipped'
              git push -q https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git ${CIRCLE_BRANCH} 
            fi
workflows:
  version: 2
  zip_and_push:
    jobs:
      - zip:
          filters:
            branches:
              only: circleci