version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo pip install awscli
      - run:
          name: Create a ZIP
          command: zip lambda.zip logdna_cloudwatch.py
      - run:
          name: Push ZIP into S3
          command: aws s3 cp lambda.zip s3://repo.logdna.com/integrations/cloudwatch/lambda.zip
      - run:
          name: Prepare  and Push Contents into S3
          command: |
            echo "botocore" >> requirements.txt
            aws s3 cp requirements.txt s3://repo.logdna.com/integrations/cloudwatch/requirements.txt
            aws s3 cp LICENSE s3://repo.logdna.com/integrations/cloudwatch/license.txt
            aws s3 cp README.md s3://repo.logdna.com/integrations/cloudwatch/readme
            aws s3 cp template.yaml s3://repo.logdna.com/integrations/cloudwatch/template.yaml