version: 2
jobs:
  zip:
    machine: true
    steps:
      - checkout
      - run:
          name: Create & Place a ZIP into bin
          command: |
            if [[ $(git log -1 --pretty=%B) == *"Zipped"* ]]; then
              echo "Inside if"
            else
              echo "Inside else"
            fi
workflows:
  version: 2
  zip_and_push:
    jobs:
      - zip:
          filters:
            branches:
              only: circleci