version: 2
jobs:
  zip_publish:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python-dev python3-dev \
              build-essential libssl-dev libffi-dev \
              libxml2-dev libxslt1-dev zlib1g-dev python-pip
            sudo pip install --upgrade pip
            sudo pip install awscli
      - run:
          name: Create a ZIP
          command: zip lambda.zip logdna_cloudwatch.py
      - run:
          name: Push into S3
          command: aws s3 cp lambda.zip s3://repo.logdna.com/integrations/cloudwatch/lambda.zip